@echo off
REM Generated by trunk tool 'markdownlint'
set PATH=C:\Users\priya\AppData\Local\trunk\tools\markdownlint\0.39.0-2f349a3b5afe99a8da495a6e6c053ad5/node_modules/.bin;C:\Users\priya\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4/bin;C:\Users\priya\AppData\Local\trunk\tools\node\18.12.1-ee91e409de31a08a96aaff7f742f83b4;C:\Users\priya\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\priya\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=
set NODE_PATH=C:\Users\priya\AppData\Local\trunk\tools\markdownlint\0.39.0-2f349a3b5afe99a8da495a6e6c053ad5/node_modules

start /w /b markdownlint %*
