@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\priya\AppData\Local\trunk\tools\osv-scanner\1.6.2-c371caf76e1396faf103e8137feb467d;C:\Users\priya\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\priya\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
