@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\priya\AppData\Local\trunk\tools\trufflehog\3.68.5-c29a45b107cf25d7b295475a0fbe9827;C:\Users\priya\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\priya\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
