action_id: trunk-upgrade-available
date: 2024-03-11 12:08:39
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\r\n"
  err: ""
timestamp: 1710158919
full_timestamp:
  nanos: 712243000
  seconds: 1710158919
trunk_version: 1.20.1
